name: CobaltStrike Docker Build

on: 
  push

jobs:
  CobaltStrike_Docker_Build:
    name: CobaltStrike Docker Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Unzip Resources
        run: |
          unzip -P'${{ secrets.PRESSURIZED_PASSWORD }}' cobaltstrike.zip -d /tmp
          unzip -P'${{ secrets.PRESSURIZED_PASSWORD }}' /tmp/cobaltstrike.zip -d .
          wget https://raw.githubusercontent.com/XRSec/CobaltStrike-Update/main/dingding.cna -O cobaltstrike/dingding.cna
          wget https://raw.githubusercontent.com/XRSec/CobaltStrike-Update/main/cs.profile -O cobaltstrike/cs.profile
          rm -rf /tmp/cobaltstrike.zip
          rm -rf cobaltstrike.zip
      - 
        name: Docker Login in Aliyun
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY_ALIYUN }}
          username: ${{ secrets.DOCKERHUB_ACCOUNT_ALIYUN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_ALIYUN }}
      - 
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:4.4
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:latest
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME_ALIYUN }}/cobaltstrike:4.4
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME_ALIYUN }}/cobaltstrike:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:4.4
            ${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:4.4.cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike:4.4.cache,mode=max
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/cobaltstrike
          
  Repository_Dispatch:
    needs: CobaltStrike_Docker_Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/CobaltStrike-Update
          event-type: CobaltStrike_Update_Action
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
